/* CREATE TABLE */ 

-- CRIANDO O BANCO DE DADOS 
CREATE DATABASE YoutubeLite;

-- MUDANDO PARA A BAASE NOVA
USE YoutubeLite;

-- CRIANDO AS TABELAS
BEGIN TRANSACTION
CREATE TABLE Canal
(
    CanalId INT PRIMARY KEY,
    Nome VARCHAR(150) NOT NULL,
    ContagemInscritos INT DEFAULT 0,
    DataCriacao DATETIME NOT NULL
);
COMMIT -- ROLLBACK;
GO

BEGIN TRANSACTION
CREATE TABLE Video
(
    VideoId INT PRIMARY KEY,
    Nome VARCHAR(150),
    Vizualizacoes INT DEFAULT 0,
    Likes INT DEFAULT 0,
    Dislikes INT DEFAULT 0,
    Duracao INT NOT NULL,
    CanalId INT,
    CONSTRAINT FK_CanalId FOREIGN KEY(CanalId)
        REFERENCES Canal(CanalId)
);
COMMIT -- ROLLBACK;
GO
