/* DELETE */

-- SINTAXE BÁSICA
DELETE
FROM NomeDaTabela
WHERE Condicao;

-- INSERE UM DADO MANDRACK
INSERT INTO Aula(Id, Nome)
VALUES(4, 'Literatura');

-- DELETA O DADO MANDRACK INSERIDO ANTERIORMENTE
DELETE 
FROM Aula 
WHERE Id = 4;
